################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\HardwareSerial.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\HardwareTimer.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\IPAddress.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\Print.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\RingBuffer.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\Stream.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\Tone.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\USBSerial.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\WInterrupts.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\WMath.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\WSerial.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\WString.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\abi.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\main.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\new.cpp \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_pulse.cpp 

C_SRCS += \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\board.c \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\hooks.c \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\itoa.c \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\pins_arduino.c \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\syscalls.c \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_analog.c \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_digital.c \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_shift.c \
E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_time.c 

C_DEPS += \
.\core\core\board.c.d \
.\core\core\hooks.c.d \
.\core\core\itoa.c.d \
.\core\core\pins_arduino.c.d \
.\core\core\syscalls.c.d \
.\core\core\wiring_analog.c.d \
.\core\core\wiring_digital.c.d \
.\core\core\wiring_shift.c.d \
.\core\core\wiring_time.c.d 

AR_OBJ += \
.\core\core\HardwareSerial.cpp.o \
.\core\core\HardwareTimer.cpp.o \
.\core\core\IPAddress.cpp.o \
.\core\core\Print.cpp.o \
.\core\core\RingBuffer.cpp.o \
.\core\core\Stream.cpp.o \
.\core\core\Tone.cpp.o \
.\core\core\USBSerial.cpp.o \
.\core\core\WInterrupts.cpp.o \
.\core\core\WMath.cpp.o \
.\core\core\WSerial.cpp.o \
.\core\core\WString.cpp.o \
.\core\core\abi.cpp.o \
.\core\core\board.c.o \
.\core\core\hooks.c.o \
.\core\core\itoa.c.o \
.\core\core\main.cpp.o \
.\core\core\new.cpp.o \
.\core\core\pins_arduino.c.o \
.\core\core\syscalls.c.o \
.\core\core\wiring_analog.c.o \
.\core\core\wiring_digital.c.o \
.\core\core\wiring_pulse.cpp.o \
.\core\core\wiring_shift.c.o \
.\core\core\wiring_time.c.o 

CPP_DEPS += \
.\core\core\HardwareSerial.cpp.d \
.\core\core\HardwareTimer.cpp.d \
.\core\core\IPAddress.cpp.d \
.\core\core\Print.cpp.d \
.\core\core\RingBuffer.cpp.d \
.\core\core\Stream.cpp.d \
.\core\core\Tone.cpp.d \
.\core\core\USBSerial.cpp.d \
.\core\core\WInterrupts.cpp.d \
.\core\core\WMath.cpp.d \
.\core\core\WSerial.cpp.d \
.\core\core\WString.cpp.d \
.\core\core\abi.cpp.d \
.\core\core\main.cpp.d \
.\core\core\new.cpp.d \
.\core\core\wiring_pulse.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
core\core\HardwareSerial.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\HardwareSerial.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\HardwareTimer.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\HardwareTimer.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\IPAddress.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\IPAddress.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\Print.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\Print.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\RingBuffer.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\RingBuffer.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\Stream.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\Stream.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\Tone.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\Tone.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\USBSerial.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\USBSerial.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\WInterrupts.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\WInterrupts.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\WMath.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\WMath.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\WSerial.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\WSerial.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\WString.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\WString.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\abi.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\abi.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\board.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\board.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\hooks.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\hooks.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\itoa.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\itoa.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\main.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\main.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\new.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\new.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\pins_arduino.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\pins_arduino.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\syscalls.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\syscalls.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_analog.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_analog.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_digital.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_digital.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_pulse.cpp.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_pulse.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu++14 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_shift.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_shift.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

core\core\wiring_time.c.o: E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino\wiring_time.c
	@echo 'Building file: $<'
	@echo 'Starting C compile'
	"E:\Sloeber\arduinoPlugin\packages\STM32\tools\arm-none-eabi-gcc\8.2.1-1.7/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb "@C:/Users/ahoel/Documents/sloeber-workspace/hyperlight_dma_sloeber/Release/sketch/build_opt.h" -c -g -Og -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -MMD "-I" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/avr" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/LL" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/hid" "-IE:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino/stm32/usb/cdc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Inc/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/STM32F4xx_HAL_Driver/Src/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/STM32F4xx/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -DSTM32F4xx -DARDUINO=10802 -DARDUINO_Hyperlight -DARDUINO_ARCH_STM32 -DBOARD_NAME="Hyperlight"  -DSTM32F407xx    "-IE:\Sloeber\arduinoPlugin\packages\STM32\tools\CMSIS\5.5.1/CMSIS/Core/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/" "-IE:\Sloeber\/arduinoPlugin/packages/STM32/hardware/stm32/1.7.0/system/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/"   -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\cores\arduino" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\variants\Hyperlight" -I"E:\Sloeber\arduinoPlugin\packages\STM32\hardware\stm32\1.7.0\libraries\IWatchdog\src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '


